return {
    [0] = {id=0, en="nothing."},
    [1] = {id=1, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [2] = {id=2, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [3] = {id=3, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [4] = {id=4, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [5] = {id=5, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [6] = {id=6, en="Restores target's HP. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [7] = {id=7, en="Restores HP of all party members within area of effect."},
    [8] = {id=8, en="Restores HP of all party members within area of effect."},
    [9] = {id=9, en="Restores HP of all party members within area of effect."},
    [10] = {id=10, en="Restores HP of all party members within area of effect."},
    [11] = {id=11, en="Restores HP of all party members within area of effect."},
    [12] = {id=12, en="Revives target from KO."},
    [13] = {id=13, en="Revives target from KO."},
    [14] = {id=14, en="Removes poison from target."},
    [15] = {id=15, en="Removes paralysis from target."},
    [16] = {id=16, en="Removes blindness from target."},
    [17] = {id=17, en="Removes silence and mute from target."},
    [18] = {id=18, en="Removes petrification from target."},
    [19] = {id=19, en="Removes disease and plague from target."},
    [20] = {id=20, en="Removes curse and bane from target."},
    [21] = {id=21, en="Deals light elemental damage to an enemy. Afflatus Solace: Increases spell potency based on the amount of HP you restore. Divine Emblem: Increases spell potency."},
    [22] = {id=22, en="Deals light elemental damage to an enemy. Afflatus Solace: Increases spell potency based on the amount of HP you restore."},
    [23] = {id=23, en="Lowers an enemy's defense and gradually deals light elemental damage."},
    [24] = {id=24, en="Lowers an enemy's defense and gradually deals light elemental damage."},
    [25] = {id=25, en="Lowers an enemy's defense and gradually deals light elemental damage."},
    [26] = {id=26, en="Lowers an enemy's defense and gradually deals light elemental damage."},
    [27] = {id=27, en="Lowers an enemy's defense and gradually deals light elemental damage."},
    [28] = {id=28, en="Deals light elemental damage to an enemy. Afflatus Misery: Increases spell potency based on the most recent damage you sustain. Divine Emblem: Increases spell potency."},
    [29] = {id=29, en="Deals light elemental damage to an enemy. Afflatus Misery: Increases spell potency based on the most recent damage you sustain. Divine Emblem: Increases spell potency."},
    [30] = {id=30, en="Deals light elemental damage to an enemy. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [31] = {id=31, en="Deals light elemental damage to an enemy. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [32] = {id=32, en="Deals light elemental damage to an enemy. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [33] = {id=33, en="Lowers defense of enemies within area of effect and gradually deals light elemental damage."},
    [34] = {id=34, en="Lowers defense of enemies within area of effect and gradually deals light elemental damage."},
    [35] = {id=35, en="Lowers defense of enemies within area of effect and gradually deals light elemental damage."},
    [36] = {id=36, en="Lowers defense of enemies within area of effect and gradually deals light elemental damage."},
    [37] = {id=37, en="Lowers defense of enemies within area of effect and gradually deals light elemental damage."},
    [38] = {id=38, en="Deals light elemental damage to enemies within area of effect. Afflatus Misery: Increases spell potency based on the most recent damage you sustain. Divine Emblem: Increases spell potency."},
    [39] = {id=39, en="Deals light elemental damage to enemies within area of effect. Afflatus Misery: Increases spell potency based on the most recent damage you sustain. Divine Emblem: Increases spell potency."},
    [40] = {id=40, en="Deals light elemental damage to enemies within area of effect. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [41] = {id=41, en="Deals light elemental damage to enemies within area of effect. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [42] = {id=42, en="Deals light elemental damage to enemies within area of effect. Afflatus Misery: Increases spell potency based on the most recent damage you sustain."},
    [43] = {id=43, en="Enhances target's defense."},
    [44] = {id=44, en="Enhances target's defense."},
    [45] = {id=45, en="Enhances target's defense."},
    [46] = {id=46, en="Enhances target's defense."},
    [47] = {id=47, en="Enhances target's defense."},
    [48] = {id=48, en="Enhances target's magic defense."},
    [49] = {id=49, en="Enhances target's magic defense."},
    [50] = {id=50, en="Enhances target's magic defense."},
    [51] = {id=51, en="Enhances target's magic defense."},
    [52] = {id=52, en="Enhances target's magic defense."},
    [53] = {id=53, en="Creates shadow images that each absorb a single attack directed at you."},
    [54] = {id=54, en="Absorbs a certain amount of damage from physical and magical attacks."},
    [55] = {id=55, en="Reduces chance of having a spell interrupted."},
    [56] = {id=56, en="Reduces an enemy's attack speed."},
    [57] = {id=57, en="Increases target's attack speed."},
    [58] = {id=58, en="Paralyzes an enemy."},
    [59] = {id=59, en="Silences an enemy."},
    [60] = {id=60, en="Increases your resistance against fire. Afflatus Solace: Grants a magic defense bonus against fire."},
    [61] = {id=61, en="Increases your resistance against ice. Afflatus Solace: Grants a magic defense bonus against ice."},
    [62] = {id=62, en="Increases your resistance against wind. Afflatus Solace: Grants a magic defense bonus against wind."},
    [63] = {id=63, en="Increases your resistance against earth. Afflatus Solace: Grants a magic defense bonus against earth."},
    [64] = {id=64, en="Increases your resistance against lightning. Afflatus Solace: Grants a magic defense bonus against lightning."},
    [65] = {id=65, en="Increases your resistance against water. Afflatus Solace: Grants a magic defense bonus against water."},
    [66] = {id=66, en="Increases resistance against fire for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against fire."},
    [67] = {id=67, en="Increases resistance against ice for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against ice."},
    [68] = {id=68, en="Increases resistance against wind for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against wind."},
    [69] = {id=69, en="Increases resistance against earth for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against earth."},
    [70] = {id=70, en="Increases resistance against lightning for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against lightning."},
    [71] = {id=71, en="Increases resistance against water for party members within area of effect. Afflatus Solace: Grants a magic defense bonus against water."},
    [72] = {id=72, en="Enhances your resistance against sleep."},
    [73] = {id=73, en="Enhances your resistance against poison."},
    [74] = {id=74, en="Enhances your resistance against paralysis."},
    [75] = {id=75, en="Enhances your resistance against blindness."},
    [76] = {id=76, en="Enhances your resistance against silence."},
    [77] = {id=77, en="Enhances your resistance against petrification."},
    [78] = {id=78, en="Enhances your resistance against disease."},
    [79] = {id=79, en="Reduces an enemy's attack speed."},
    [80] = {id=80, en="Paralyzes an enemy."},
    [81] = {id=81, en="Transports qualified party members within area of effect to Jugner Forest [S]."},
    [82] = {id=82, en="Transports qualified party members within area of effect to Pashhow Marshlands [S]."},
    [83] = {id=83, en="Transports qualified party members within area of effect to the Meriphataud Mountains [S]."},
    [84] = {id=84, en="Enhances your resistance against amnesia."},
    [85] = {id=85, en="Enhances resistance against amnesia for party members within area of effect."},
    [86] = {id=86, en="Enhances resistance against sleep for party members within area of effect."},
    [87] = {id=87, en="Enhances resistance against poison for party members within area of effect."},
    [88] = {id=88, en="Enhances resistance against paralysis for party members within area of effect."},
    [89] = {id=89, en="Enhances resistance against blindness for party members within area of effect."},
    [90] = {id=90, en="Enhances resistance against silence for party members within area of effect."},
    [91] = {id=91, en="Enhances resistance against petrification for party members within area of effect."},
    [92] = {id=92, en="Enhances resistance against disease for party members within area of effect."},
    [93] = {id=93, en="Restores HP for party members within area of effect. Afflatus Misery: Increases healing potency."},
    [94] = {id=94, en="Transfers one enfeebling effect from target party member to yourself. Afflatus Solace: Increases effect removal potency."},
    [95] = {id=95, en="Removes one enfeebling effect you have from yourself and party members within area of effect. Afflatus Misery: Increases effect removal potency."},
    [96] = {id=96, en="Reduces TP dealt when striking an enemy for party members within area of effect. Afflatus Misery: Adds light damage to your initial attacks and bestows an accuracy bonus when target is missed."},
    [97] = {id=97, en="Increases chance of blocking with shield, and reflects portion of blocked damage back to attacker."},
    [98] = {id=98, en="Puts an enemy to sleep."},
    [99] = {id=99, en="Changes the weather around target party member to 'dusty.'"},
    [100] = {id=100, en="Adds fire damage to your attacks."},
    [101] = {id=101, en="Adds ice damage to your attacks."},
    [102] = {id=102, en="Adds wind damage to your attacks."},
    [103] = {id=103, en="Adds earth damage to your attacks."},
    [104] = {id=104, en="Adds lightning damage to your attacks."},
    [105] = {id=105, en="Adds water damage to your attacks."},
    [106] = {id=106, en="Gives you a certain amount of damage resistance."},
    [107] = {id=107, en="Grants a party member a certain amount of damage resistance."},
    [108] = {id=108, en="Gradually restores target's HP."},
    [109] = {id=109, en="Gradually restores target's MP."},
    [110] = {id=110, en="Gradually restores target's HP."},
    [111] = {id=111, en="Gradually restores target's HP."},
    [112] = {id=112, en="Temporarily blinds an enemy, greatly lowers its accuracy."},
    [113] = {id=113, en="Changes the weather around target party member to 'rainy.'"},
    [114] = {id=114, en="Changes the weather around target party member to 'windy.'"},
    [115] = {id=115, en="Changes the weather around target party member to 'hot.'"},
    [116] = {id=116, en="Changes the weather around target party member to 'snowy.'"},
    [117] = {id=117, en="Changes the weather around target party member to 'thundery.'"},
    [118] = {id=118, en="Changes the weather around target party member to 'gloomy.'"},
    [119] = {id=119, en="Changes the weather around target party member to 'auroras.'"},
    [120] = {id=120, en="Transports qualified party members within area of effect to Yhoator."},
    [121] = {id=121, en="Transports qualified party members within area of effect to Altepa."},
    [122] = {id=122, en="Transports qualified party members within area of effect to Holla."},
    [123] = {id=123, en="Transports qualified party members within area of effect to Dem."},
    [124] = {id=124, en="Transports qualified party members within area of effect to Mea."},
    [125] = {id=125, en="Enhances defense for party members within area of effect."},
    [126] = {id=126, en="Enhances defense for party members within area of effect."},
    [127] = {id=127, en="Enhances defense for party members within area of effect."},
    [128] = {id=128, en="Enhances defense for party members within area of effect."},
    [129] = {id=129, en="Enhances defense for party members within area of effect."},
    [130] = {id=130, en="Enhances magic defense for party members within area of effect."},
    [131] = {id=131, en="Enhances magic defense for party members within area of effect."},
    [132] = {id=132, en="Enhances magic defense for party members within area of effect."},
    [133] = {id=133, en="Enhances magic defense for party members within area of effect."},
    [134] = {id=134, en="Enhances magic defense for party members within area of effect."},
    [135] = {id=135, en="Grants you the effect of Raise when you are KO'd."},
    [136] = {id=136, en="Lessens chance of being detected by sight."},
    [137] = {id=137, en="Lessens chance of being detected by sound."},
    [138] = {id=138, en="Lessens chance of being detected by smell."},
    [139] = {id=139, en="Transports qualified party members within area of effect to Xarcabard."},
    [140] = {id=140, en="Revives target from KO."},
    [141] = {id=141, en="Grants you the effect of Raise II when you are KO'd."},
    [142] = {id=142, en="Grants you the effect of Raise III when you are KO'd."},
    [143] = {id=143, en="Removes one detrimental magic effect from target party member."},
    [144] = {id=144, en="Deals fire damage to an enemy."},
    [145] = {id=145, en="Deals fire damage to an enemy."},
    [146] = {id=146, en="Deals fire damage to an enemy."},
    [147] = {id=147, en="Deals fire damage to an enemy."},
    [148] = {id=148, en="Deals fire damage to an enemy."},
    [149] = {id=149, en="Deals ice damage to an enemy."},
    [150] = {id=150, en="Deals ice damage to an enemy."},
    [151] = {id=151, en="Deals ice damage to an enemy."},
    [152] = {id=152, en="Deals ice damage to an enemy."},
    [153] = {id=153, en="Deals ice damage to an enemy."},
    [154] = {id=154, en="Deals wind damage to an enemy."},
    [155] = {id=155, en="Deals wind damage to an enemy."},
    [156] = {id=156, en="Deals wind damage to an enemy."},
    [157] = {id=157, en="Deals wind damage to an enemy."},
    [158] = {id=158, en="Deals wind damage to an enemy."},
    [159] = {id=159, en="Deals earth damage to an enemy."},
    [160] = {id=160, en="Deals earth damage to an enemy."},
    [161] = {id=161, en="Deals earth damage to an enemy."},
    [162] = {id=162, en="Deals earth damage to an enemy."},
    [163] = {id=163, en="Deals earth damage to an enemy."},
    [164] = {id=164, en="Deals lightning damage to an enemy."},
    [165] = {id=165, en="Deals lightning damage to an enemy."},
    [166] = {id=166, en="Deals lightning damage to an enemy."},
    [167] = {id=167, en="Deals lightning damage to an enemy."},
    [168] = {id=168, en="Deals lightning damage to an enemy."},
    [169] = {id=169, en="Deals water damage to an enemy."},
    [170] = {id=170, en="Deals water damage to an enemy."},
    [171] = {id=171, en="Deals water damage to an enemy."},
    [172] = {id=172, en="Deals water damage to an enemy."},
    [173] = {id=173, en="Deals water damage to an enemy."},
    [174] = {id=174, en="Deals fire damage to enemies within area of effect."},
    [175] = {id=175, en="Deals fire damage to enemies within area of effect."},
    [176] = {id=176, en="Deals fire damage to enemies within area of effect."},
    [177] = {id=177, en="Deals fire damage to enemies within area of effect."},
    [178] = {id=178, en="Deals fire damage to enemies within area of effect."},
    [179] = {id=179, en="Deals ice damage to enemies within area of effect."},
    [180] = {id=180, en="Deals ice damage to enemies within area of effect."},
    [181] = {id=181, en="Deals ice damage to enemies within area of effect."},
    [182] = {id=182, en="Deals ice damage to enemies within area of effect."},
    [183] = {id=183, en="Deals ice damage to enemies within area of effect."},
    [184] = {id=184, en="Deals wind damage to enemies within area of effect."},
    [185] = {id=185, en="Deals wind damage to enemies within area of effect."},
    [186] = {id=186, en="Deals wind damage to enemies within area of effect."},
    [187] = {id=187, en="Deals wind damage to enemies within area of effect."},
    [188] = {id=188, en="Deals wind damage to enemies within area of effect."},
    [189] = {id=189, en="Deals earth damage to enemies within area of effect."},
    [190] = {id=190, en="Deals earth damage to enemies within area of effect."},
    [191] = {id=191, en="Deals earth damage to enemies within area of effect."},
    [192] = {id=192, en="Deals earth damage to enemies within area of effect."},
    [193] = {id=193, en="Deals earth damage to enemies within area of effect."},
    [194] = {id=194, en="Deals lightning damage to enemies within area of effect."},
    [195] = {id=195, en="Deals lightning damage to enemies within area of effect."},
    [196] = {id=196, en="Deals lightning damage to enemies within area of effect."},
    [197] = {id=197, en="Deals lightning damage to enemies within area of effect."},
    [198] = {id=198, en="Deals lightning damage to enemies within area of effect."},
    [199] = {id=199, en="Deals water damage to enemies within area of effect."},
    [200] = {id=200, en="Deals water damage to enemies within area of effect."},
    [201] = {id=201, en="Deals water damage to enemies within area of effect."},
    [202] = {id=202, en="Deals water damage to enemies within area of effect."},
    [203] = {id=203, en="Deals water damage to enemies within area of effect."},
    [204] = {id=204, en="Deals fire damage to an enemy and lowers its resistance against water."},
    [205] = {id=205, en="Deals fire damage to an enemy and lowers its resistance against water."},
    [206] = {id=206, en="Deals ice damage to an enemy and lowers its resistance against fire."},
    [207] = {id=207, en="Deals ice damage to an enemy and lowers its resistance against fire."},
    [208] = {id=208, en="Deals wind damage to an enemy and lowers its resistance against ice."},
    [209] = {id=209, en="Deals wind damage to an enemy and lowers its resistance against ice."},
    [210] = {id=210, en="Deals earth damage to an enemy and lowers its resistance against wind."},
    [211] = {id=211, en="Deals earth damage to an enemy and lowers its resistance against wind."},
    [212] = {id=212, en="Deals lightning damage to an enemy and lowers its resistance against earth."},
    [213] = {id=213, en="Deals lightning damage to an enemy and lowers its resistance against earth."},
    [214] = {id=214, en="Deals water damage to an enemy and lowers its resistance against lightning."},
    [215] = {id=215, en="Deals water damage to an enemy and lowers its resistance against lightning."},
    [216] = {id=216, en="Weighs an enemy down and lowers its movement speed."},
    [217] = {id=217, en="Weighs an enemy down and lowers its movement speed."},
    [218] = {id=218, en="Summons a massive meteor from the heavens to smite your foes."},
    [219] = {id=219, en="Deals dark damage to an enemy. Successive use enhances spell potency."},
    [220] = {id=220, en="Poisons an enemy and gradually reduces its HP."},
    [221] = {id=221, en="Poisons an enemy and gradually reduces its HP."},
    [222] = {id=222, en="Poisons an enemy and gradually reduces its HP."},
    [223] = {id=223, en="Poisons an enemy and gradually reduces its HP."},
    [224] = {id=224, en="Poisons an enemy and gradually reduces its HP."},
    [225] = {id=225, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [226] = {id=226, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [227] = {id=227, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [228] = {id=228, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [229] = {id=229, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [230] = {id=230, en="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP."},
    [231] = {id=231, en="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP."},
    [232] = {id=232, en="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP."},
    [233] = {id=233, en="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP."},
    [234] = {id=234, en="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP."},
    [235] = {id=235, en="Deals fire damage that lowers an enemy's Intelligence and gradually reduces its HP."},
    [236] = {id=236, en="Deals ice damage that lowers an enemy's Agility and gradually reduces its HP."},
    [237] = {id=237, en="Deals wind damage that lowers an enemy's Vitality and gradually reduces its HP."},
    [238] = {id=238, en="Deals earth damage that lowers an enemy's Dexterity and gradually reduces its HP."},
    [239] = {id=239, en="Deals lightning damage that lowers an enemy's Mind and gradually reduces its HP."},
    [240] = {id=240, en="Deals water damage that lowers an enemy's Strength and gradually reduces its HP."},
    [241] = {id=241, en="Transports qualified target party member to their nation of allegiance in the past."},
    [242] = {id=242, en="Steals an enemy's accuracy."},
    [243] = {id=243, en="Steals an enemy's beneficial status effects."},
    [244] = {id=244, en="Magic Help Message."},
    [245] = {id=245, en="Steals an enemy's HP. Ineffective against undead."},
    [246] = {id=246, en="Steals an enemy's HP, potentially increasing maximum HP. Ineffective against undead."},
    [247] = {id=247, en="Steals an enemy's MP. Ineffective against undead."},
    [248] = {id=248, en="Steals an enemy's MP. Ineffective against undead."},
    [249] = {id=249, en="Covers you with magical fire spikes. Enemies that hit you take fire damage."},
    [250] = {id=250, en="Covers you with magical ice spikes. Enemies that hit you take ice damage."},
    [251] = {id=251, en="Covers you with magical lightning spikes. Enemies that hit you take lightning damage."},
    [252] = {id=252, en="Temporarily prevents an enemy from acting."},
    [253] = {id=253, en="Puts an enemy to sleep."},
    [254] = {id=254, en="Blinds an enemy, lowers its accuracy."},
    [255] = {id=255, en="Petrifies an enemy, preventing it from acting."},
    [256] = {id=256, en="Gives an enemy a disease that prevents it from recovering HP and MP."},
    [257] = {id=257, en="Puts a curse on an enemy, reducing its maximum HP and MP."},
    [258] = {id=258, en="Binds an enemy in place, immobilizing it."},
    [259] = {id=259, en="Puts an enemy to sleep."},
    [260] = {id=260, en="Removes one beneficial magic effect from an enemy."},
    [261] = {id=261, en="Transports you to your home point."},
    [262] = {id=262, en="Transports target party member to their home point."},
    [263] = {id=263, en="Transports party members within area of effect out of a dungeon."},
    [264] = {id=264, en="Drags a KO'd target toward you."},
    [265] = {id=265, en="Drags a KO'd target toward you."},
    [266] = {id=266, en="Steals an enemy's Strength."},
    [267] = {id=267, en="Steals an enemy's Dexterity."},
    [268] = {id=268, en="Steals an enemy's Vitality."},
    [269] = {id=269, en="Steals an enemy's Agility."},
    [270] = {id=270, en="Steals an enemy's Intelligence."},
    [271] = {id=271, en="Steals an enemy's Mind."},
    [272] = {id=272, en="Steals an enemy's Charisma."},
    [273] = {id=273, en="Puts all enemies within area of effect to sleep."},
    [274] = {id=274, en="Puts all enemies within area of effect to sleep."},
    [275] = {id=275, en="Steals an enemy's TP."},
    [276] = {id=276, en="Blinds an enemy, lowers its accuracy."},
    [277] = {id=277, en="Covers you with magical darkness spikes. Steals HP from enemies that hit you. Ineffective against undead."},
    [278] = {id=278, en="Deals earth damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [279] = {id=279, en="Deals water damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [280] = {id=280, en="Deals wind damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [281] = {id=281, en="Deals fire damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [282] = {id=282, en="Deals ice damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [283] = {id=283, en="Deals lightning damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [284] = {id=284, en="Deals darkness damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [285] = {id=285, en="Deals light damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [286] = {id=286, en="Decreases an enemy's magic accuracy and increases its spellcasting time."},
    [287] = {id=287, en="Increases the magic accuracy for spells of the same element as the current weather."},
    [288] = {id=288, en="Summons a Fire Spirit to fight by your side."},
    [289] = {id=289, en="Summons an Ice Spirit to fight by your side."},
    [290] = {id=290, en="Summons an Air Spirit to fight by your side."},
    [291] = {id=291, en="Summons an Earth Spirit to fight by your side."},
    [292] = {id=292, en="Summons a Thunder Spirit to fight by your side."},
    [293] = {id=293, en="Summons a Water Spirit to fight by your side."},
    [294] = {id=294, en="Summons a Light Spirit to fight by your side."},
    [295] = {id=295, en="Summons a Dark Spirit to fight by your side."},
    [296] = {id=296, en="Summons Carbuncle to fight by your side."},
    [297] = {id=297, en="Summons Fenrir to fight by your side."},
    [298] = {id=298, en="Summons Ifrit to fight by your side."},
    [299] = {id=299, en="Summons Titan to fight by your side."},
    [300] = {id=300, en="Summons Leviathan to fight by your side."},
    [301] = {id=301, en="Summons Garuda to fight by your side."},
    [302] = {id=302, en="Summons Shiva to fight by your side."},
    [303] = {id=303, en="Summons Ramuh to fight by your side."},
    [304] = {id=304, en="Summons Diabolos to fight by your side."},
    [305] = {id=305, en="Summons Odin to fight by your side."},
    [306] = {id=306, en="Summons Alexander to fight by your side."},
    [307] = {id=307, en="Summons Cait Sith to fight by your side."},
    [308] = {id=308, en="Facilitates enmity gain for target party member."},
    [309] = {id=309, en="Suppresses enmity gain for target party member."},
    [310] = {id=310, en="Adds light damage to your attacks."},
    [311] = {id=311, en="Adds darkness damage to your attacks."},
    [312] = {id=312, en="Adds fire damage to your initial attacks and reduces the target's resistance against water."},
    [313] = {id=313, en="Adds ice damage to your initial attacks and reduces the target's resistance against fire."},
    [314] = {id=314, en="Adds wind damage to your initial attacks and reduces the target's resistance against ice."},
    [315] = {id=315, en="Adds earth damage to your initial attacks and reduces the target's resistance against wind."},
    [316] = {id=316, en="Adds lightning damage to your initial attacks and reduces the target's resistance against earth."},
    [317] = {id=317, en="Adds water damage to your initial attacks and reduces the target's resistance against lightning."},
    [318] = {id=318, en="Uses the ninja tool 'sanjaku-tenugui.' Lessens chance of being detected by sound."},
    [319] = {id=319, en="Uses the ninja tool 'soshi.' Weakens an enemy's attack."},
    [320] = {id=320, en="Uses the ninja tool 'uchitake.' Deals fire damage to an enemy and lowers its resistance against water."},
    [321] = {id=321, en="Uses the ninja tool 'uchitake.' Deals fire damage to an enemy and lowers its resistance against water."},
    [322] = {id=322, en="Uses the ninja tool 'uchitake.' Deals fire damage to an enemy and lowers its resistance against water."},
    [323] = {id=323, en="Uses the ninja tool 'tsurara.' Deals ice damage to an enemy and lowers its resistance against fire."},
    [324] = {id=324, en="Uses the ninja tool 'tsurara.' Deals ice damage to an enemy and lowers its resistance against fire."},
    [325] = {id=325, en="Uses the ninja tool 'tsurara.' Deals ice damage to an enemy and lowers its resistance against fire."},
    [326] = {id=326, en="Uses the ninja tool 'kawahori-ogi.' Deals wind damage to an enemy and lowers its resistance against ice."},
    [327] = {id=327, en="Uses the ninja tool 'kawahori-ogi.' Deals wind damage to an enemy and lowers its resistance against ice."},
    [328] = {id=328, en="Uses the ninja tool 'kawahori-ogi.' Deals wind damage to an enemy and lowers its resistance against ice."},
    [329] = {id=329, en="Uses the ninja tool 'makibishi.' Deals earth damage to an enemy and lowers its resistance against wind."},
    [330] = {id=330, en="Uses the ninja tool 'makibishi.' Deals earth damage to an enemy and lowers its resistance against wind."},
    [331] = {id=331, en="Uses the ninja tool 'makibishi.' Deals earth damage to an enemy and lowers its resistance against wind."},
    [332] = {id=332, en="Uses the ninja tool 'hiraishin.' Deals lightning damage to an enemy and lowers its resistance against earth."},
    [333] = {id=333, en="Uses the ninja tool 'hiraishin.' Deals lightning damage to an enemy and lowers its resistance against earth."},
    [334] = {id=334, en="Uses the ninja tool 'hiraishin.' Deals lightning damage to an enemy and lowers its resistance against earth."},
    [335] = {id=335, en="Uses the ninja tool 'mizu-deppo.' Deals water damage to an enemy and lowers its resistance against lightning."},
    [336] = {id=336, en="Uses the ninja tool 'mizu-deppo.' Deals water damage to an enemy and lowers its resistance against lightning."},
    [337] = {id=337, en="Uses the ninja tool 'mizu-deppo.' Deals water damage to an enemy and lowers its resistance against lightning."},
    [338] = {id=338, en="Uses the ninja tool 'shihei.' Creates shadow images that each absorb a single attack directed at you."},
    [339] = {id=339, en="Uses the ninja tool 'shihei.' Creates shadow images that each absorb a single attack directed at you."},
    [340] = {id=340, en="Uses the ninja tool 'shihei.' Creates shadow images that each absorb a single attack directed at you."},
    [341] = {id=341, en="Uses the ninja tool 'jusatsu.' Paralyzes an enemy."},
    [342] = {id=342, en="Uses the ninja tool 'jusatsu.' Paralyzes an enemy."},
    [343] = {id=343, en="Uses the ninja tool 'jusatsu.' Paralyzes an enemy."},
    [344] = {id=344, en="Uses the ninja tool 'kaginawa.' Reduces an enemy's attack speed."},
    [345] = {id=345, en="Uses the ninja tool 'kaginawa.' Reduces an enemy's attack speed."},
    [346] = {id=346, en="Uses the ninja tool 'kaginawa.' Reduces an enemy's attack speed."},
    [347] = {id=347, en="Uses the ninja tool 'sairui-ran.' Blinds an enemy."},
    [348] = {id=348, en="Uses the ninja tool 'sairui-ran.' Blinds an enemy."},
    [349] = {id=349, en="Uses the ninja tool 'sairui-ran.' Blinds an enemy."},
    [350] = {id=350, en="Uses the ninja tool 'kodoku.' Poisons an enemy."},
    [351] = {id=351, en="Uses the ninja tool 'kodoku.' Poisons an enemy."},
    [352] = {id=352, en="Uses the ninja tool 'kodoku.' Poisons an enemy."},
    [353] = {id=353, en="Uses the ninja tool 'shinobi-tabi.' Lessens chance of being detected by sight."},
    [354] = {id=354, en="Uses the ninja tool 'shinobi-tabi.' Lessens chance of being detected by sight."},
    [355] = {id=355, en="Summons Siren to fight by your side."},
    [356] = {id=356, en="Magic Help Message."},
    [357] = {id=357, en="Magic Help Message."},
    [358] = {id=358, en="Magic Help Message."},
    [359] = {id=359, en="Magic Help Message."},
    [360] = {id=360, en="Removes one beneficial magic effect from enemies in area of effect."},
    [361] = {id=361, en="Magic Help Message."},
    [362] = {id=362, en="Magic Help Message."},
    [363] = {id=363, en="Magic Help Message."},
    [364] = {id=364, en="Magic Help Message."},
    [365] = {id=365, en="Petrifies enemies within area of effect, preventing them from acting."},
    [366] = {id=366, en="Magic Help Message."},
    [367] = {id=367, en="Consumes all MP. Has a chance to knock out the target. If Death fails to knock out the target, it will instead deal darkness damage. Ineffective against undead."},
    [368] = {id=368, en="Deals sonic damage to enemies."},
    [369] = {id=369, en="Deals sonic damage to enemies."},
    [370] = {id=370, en="Deals sonic damage to enemies."},
    [371] = {id=371, en="Deals sonic damage to enemies."},
    [372] = {id=372, en="Deals sonic damage to enemies."},
    [373] = {id=373, en="Deals sonic damage to enemies."},
    [374] = {id=374, en="Deals sonic damage to enemies."},
    [375] = {id=375, en="Deals sonic damage to enemies."},
    [376] = {id=376, en="Puts enemies within area of effect to sleep."},
    [377] = {id=377, en="Puts enemies within area of effect to sleep."},
    [378] = {id=378, en="Gradually restores HP for party members within area of effect."},
    [379] = {id=379, en="Gradually restores HP for party members within area of effect."},
    [380] = {id=380, en="Gradually restores HP for party members within area of effect."},
    [381] = {id=381, en="Gradually restores HP for party members within area of effect."},
    [382] = {id=382, en="Gradually restores HP for party members within area of effect."},
    [383] = {id=383, en="Gradually restores HP for party members within area of effect."},
    [384] = {id=384, en="Gradually restores HP for party members within area of effect."},
    [385] = {id=385, en="Gradually restores HP for party members within area of effect."},
    [386] = {id=386, en="Gradually restores MP for party members within area of effect."},
    [387] = {id=387, en="Gradually restores MP for party members within area of effect."},
    [388] = {id=388, en="Gradually restores MP for party members within area of effect."},
    [389] = {id=389, en="Enhances defense for party members within area of effect."},
    [390] = {id=390, en="Enhances defense for party members within area of effect."},
    [391] = {id=391, en="Enhances defense for party members within area of effect."},
    [392] = {id=392, en="Enhances defense for party members within area of effect."},
    [393] = {id=393, en="Enhances defense for party members within area of effect."},
    [394] = {id=394, en="Enhances attacks for party members within area of effect."},
    [395] = {id=395, en="Enhances attacks for party members within area of effect."},
    [396] = {id=396, en="Enhances attacks for party members within area of effect."},
    [397] = {id=397, en="Enhances attacks for party members within area of effect."},
    [398] = {id=398, en="Enhances attacks for party members within area of effect."},
    [399] = {id=399, en="Enhances melee attack accuracy for party members within area of effect."},
    [400] = {id=400, en="Enhances melee attack accuracy for party members within area of effect."},
    [401] = {id=401, en="Enhances ranged attack accuracy for party members within area of effect."},
    [402] = {id=402, en="Enhances ranged attack accuracy for party members within area of effect."},
    [403] = {id=403, en="Enhances evasion for party members within area of effect."},
    [404] = {id=404, en="Enhances evasion for party members within area of effect."},
    [405] = {id=405, en="Enhances resistance against sleep for party members within area of effect."},
    [406] = {id=406, en="Enhances resistance against poison for party members within area of effect."},
    [407] = {id=407, en="Enhances resistance against paralysis for party members within area of effect."},
    [408] = {id=408, en="Enhances resistance against blindness for party members within area of effect."},
    [409] = {id=409, en="Enhances resistance against silence for party members within area of effect."},
    [410] = {id=410, en="Enhances resistance against silence for party members within area of effect."},
    [411] = {id=411, en="Enhances resistance against silence for party members within area of effect."},
    [412] = {id=412, en="Enhances resistance against petrification for party members within area of effect."},
    [413] = {id=413, en="Enhances resistance against disease for party members within area of effect."},
    [414] = {id=414, en="Enhances resistance against curse for party members within area of effect."},
    [415] = {id=415, en="Enhances resistance against bind for party members within area of effect."},
    [416] = {id=416, en="Enhances resistance against weight for party members within area of effect."},
    [417] = {id=417, en="Increases attack and accuracy for party members within area of effect. Also decreases attack delay."},
    [418] = {id=418, en="Enhances resistance against charm for party members within area of effect."},
    [419] = {id=419, en="Increases attack speed for party members within area of effect."},
    [420] = {id=420, en="Increases attack speed for party members within area of effect."},
    [421] = {id=421, en="Reduces an enemy's attack speed."},
    [422] = {id=422, en="Reduces an enemy's attack speed."},
    [423] = {id=423, en="Reduces an enemy's attack speed."},
    [424] = {id=424, en="Enhances Strength for party members within area of effect."},
    [425] = {id=425, en="Enhances Dexterity for party members within area of effect."},
    [426] = {id=426, en="Enhances Vitality for party members within area of effect."},
    [427] = {id=427, en="Enhances Agility for party members within area of effect."},
    [428] = {id=428, en="Enhances Intelligence for party members within area of effect."},
    [429] = {id=429, en="Enhances Mind for party members within area of effect."},
    [430] = {id=430, en="Enhances Charisma for party members within area of effect."},
    [431] = {id=431, en="Enhances Strength for party members within area of effect."},
    [432] = {id=432, en="Enhances Dexterity for party members within area of effect."},
    [433] = {id=433, en="Enhances Vitality for party members within area of effect."},
    [434] = {id=434, en="Enhances Agility for party members within area of effect."},
    [435] = {id=435, en="Enhances Intelligence for party members within area of effect."},
    [436] = {id=436, en="Enhances Mind for party members within area of effect."},
    [437] = {id=437, en="Enhances Charisma for party members within area of effect."},
    [438] = {id=438, en="Increases resistance against fire for party members within area of effect."},
    [439] = {id=439, en="Increases resistance against ice for party members within area of effect."},
    [440] = {id=440, en="Increases resistance against wind for party members within area of effect."},
    [441] = {id=441, en="Increases resistance against earth for party members within area of effect."},
    [442] = {id=442, en="Increases resistance against lightning for party members within area of effect."},
    [443] = {id=443, en="Increases resistance against water for party members within area of effect."},
    [444] = {id=444, en="Increases resistance against light for party members within area of effect."},
    [445] = {id=445, en="Increases resistance against darkness for party members within area of effect."},
    [446] = {id=446, en="Increases resistance against fire and sometimes nullifies fire damage for party members within area of effect."},
    [447] = {id=447, en="Increases resistance against ice and sometimes nullifies ice damage for party members within area of effect."},
    [448] = {id=448, en="Increases resistance against wind and sometimes nullifies wind damage for party members within area of effect."},
    [449] = {id=449, en="Increases resistance against earth and sometimes nullifies earth damage for party members within area of effect."},
    [450] = {id=450, en="Increases resistance against lightning and sometimes nullifies lightning damage for party members within area of effect."},
    [451] = {id=451, en="Increases resistance against water and sometimes nullifies water damage for party members within area of effect."},
    [452] = {id=452, en="Increases resistance against light and sometimes nullifies light damage for party members within area of effect."},
    [453] = {id=453, en="Increases resistance against darkness and sometimes nullifies darkness damage for party members within area of effect."},
    [454] = {id=454, en="Reduces an enemy's resistance against fire."},
    [455] = {id=455, en="Reduces an enemy's resistance against ice."},
    [456] = {id=456, en="Reduces an enemy's resistance against wind."},
    [457] = {id=457, en="Reduces an enemy's resistance against earth."},
    [458] = {id=458, en="Reduces an enemy's resistance against lightning."},
    [459] = {id=459, en="Reduces an enemy's resistance against water."},
    [460] = {id=460, en="Reduces an enemy's resistance against light."},
    [461] = {id=461, en="Reduces an enemy's resistance against darkness."},
    [462] = {id=462, en="Removes one beneficial magic effect from an enemy."},
    [463] = {id=463, en="Puts an enemy to sleep."},
    [464] = {id=464, en="Grants Reraise to party members within area of effect."},
    [465] = {id=465, en="Increases movement speed for party members within area of effect."},
    [466] = {id=466, en="Charms an enemy."},
    [467] = {id=467, en="Increases movement speed for party members within area of effect."},
    [468] = {id=468, en="Reduces enmity loss for party members within area of effect."},
    [469] = {id=469, en="Reduces enmity for party members within area of effect."},
    [470] = {id=470, en="Mitigates the impact of severely damaging attacks for party members within area of effect."},
    [471] = {id=471, en="Puts an enemy to sleep."},
    [472] = {id=472, en="Decreases an enemy's magic accuracy and increases its spellcasting time."},
    [473] = {id=473, en="Gradually restores target's MP."},
    [474] = {id=474, en="Restores HP for party members within area of effect. Afflatus Misery: Increases healing potency."},
    [475] = {id=475, en="Restores HP for party members within area of effect. Afflatus Misery: Increases healing potency."},
    [476] = {id=476, en="Facilitates enmity gain."},
    [477] = {id=477, en="Gradually restores target's HP."},
    [478] = {id=478, en="Consumes 20% of your maximum MP. Gradually restores target's HP and MP and increases attack speed."},
    [479] = {id=479, en="Enhances Strength for party members within area of effect."},
    [480] = {id=480, en="Enhances Dexterity for party members within area of effect."},
    [481] = {id=481, en="Enhances Vitality for party members within area of effect."},
    [482] = {id=482, en="Enhances Agility for party members within area of effect."},
    [483] = {id=483, en="Enhances Intelligence for party members within area of effect."},
    [484] = {id=484, en="Enhances Mind for party members within area of effect."},
    [485] = {id=485, en="Enhances Charisma for party members within area of effect."},
    [486] = {id=486, en="Enhances Strength."},
    [487] = {id=487, en="Enhances Dexterity."},
    [488] = {id=488, en="Enhances Vitality."},
    [489] = {id=489, en="Enhances Agility."},
    [490] = {id=490, en="Enhances Intelligence."},
    [491] = {id=491, en="Enhances Mind."},
    [492] = {id=492, en="Enhances Charisma."},
    [493] = {id=493, en="Grants the ability to occasionally attack twice."},
    [494] = {id=494, en="Revives target from KO and bestows a Reraise effect."},
    [495] = {id=495, en="Gradually increases target's TP."},
    [496] = {id=496, en="Deals fire damage to enemies within area of effect. Successive use enhances spell potency."},
    [497] = {id=497, en="Deals ice damage to enemies within area of effect. Successive use enhances spell potency."},
    [498] = {id=498, en="Deals wind damage to enemies within area of effect. Successive use enhances spell potency."},
    [499] = {id=499, en="Deals earth damage to enemies within area of effect. Successive use enhances spell potency."},
    [500] = {id=500, en="Deals thunder damage to enemies within area of effect. Successive use enhances spell potency."},
    [501] = {id=501, en="Deals water damage to enemies within area of effect. Successive use enhances spell potency."},
    [502] = {id=502, en="Consumes 20% of your maximum MP. Relentless dark damage slowly devours an enemy."},
    [503] = {id=503, en="Deals dark damage that lowers an enemy's Strength, Dexterity, Vitality, Agility, Intelligence, Mind, and Charisma."},
    [504] = {id=504, en="Gradually restores target's HP."},
    [505] = {id=505, en="Uses the ninja tool 'ranka.' Facilitates enmity gain."},
    [506] = {id=506, en="Uses the ninja tool 'furusumi.' Suppresses enmity gain."},
    [507] = {id=507, en="Uses the ninja tool 'kabenro.' Reduces TP dealt when striking an enemy."},
    [508] = {id=508, en="Uses the ninja tool 'jinko.' Reduces an enemy's TP gain."},
    [509] = {id=509, en="Uses the ninja tool 'ryuno.' Increases your TP gain."},
    [510] = {id=510, en="Uses the ninja tool 'mokujin.' Makes you immune to severely damaging attacks."},
    [511] = {id=511, en="Increases target's attack speed."},
    [512] = {id=512, en="a line help text"},
    [513] = {id=513, en="Poisons enemies within range and gradually reduces their HP."},
    [514] = {id=514, en="a line help text"},
    [515] = {id=515, en="Deals water damage to enemies within range. Additional effect: STR Down."},
    [516] = {id=516, en="a line help text"},
    [517] = {id=517, en="Absorbs a certain amount of damage from physical and magical attacks."},
    [518] = {id=518, en="a line help text"},
    [519] = {id=519, en="Deals critical damage. Chance of critical hit varies with TP."},
    [520] = {id=520, en="a line help text"},
    [521] = {id=521, en="Steals an enemy's MP. Ineffective against undead."},
    [522] = {id=522, en="Deals dark damage to an enemy."},
    [523] = {id=523, en="a line help text"},
    [524] = {id=524, en="Deals earth damage to enemies within range. Additional effect: Accuracy Down."},
    [525] = {id=525, en="a line help text"},
    [526] = {id=526, en="a line help text"},
    [527] = {id=527, en="Damage varies with TP."},
    [528] = {id=528, en="a line help text"},
    [529] = {id=529, en="Delivers a threefold attack. Accuracy varies with TP."},
    [530] = {id=530, en="Increases attack speed."},
    [531] = {id=531, en="Deals ice damage to enemies within range. Additional effect: 'Bind.'"},
    [532] = {id=532, en="Deals lightning damage to an enemy. Additional effect: 'Stun.'"},
    [533] = {id=533, en="Sacrifices HP to damage enemies within range. Affects caster with Weakness."},
    [534] = {id=534, en="Deals wind damage to enemies within range. Additional effect: Weight."},
    [535] = {id=535, en="Deals ice damage that lowers Agility and gradually reduces HP of enemies within range."},
    [536] = {id=536, en="Deals water damage to enemies within a fan-shaped area originating from the caster. Additional effect: Poison."},
    [537] = {id=537, en="Lowers Vitality of enemies within range."},
    [538] = {id=538, en="Enhances magic attack."},
    [539] = {id=539, en="Additional effect: Weakens attacks. Accuracy varies with TP."},
    [540] = {id=540, en="Accuracy varies with TP."},
    [541] = {id=541, en="Steals HP from enemies within range. Ineffective against undead."},
    [542] = {id=542, en="Steals an enemy's HP. Ineffective against undead."},
    [543] = {id=543, en="Damage varies with TP."},
    [544] = {id=544, en="Deals water damage to enemies within area of effect."},
    [545] = {id=545, en="Deals critical damage. Chance of critical hit varies with TP."},
    [546] = {id=546, en="a line help text"},
    [547] = {id=547, en="Enhances defense."},
    [548] = {id=548, en="Reduces the attack speed of enemies within a fan-shaped area originating from the caster."},
    [549] = {id=549, en="Restores HP."},
    [550] = {id=550, en="a line help text"},
    [551] = {id=551, en="Deals critical damage. Chance of critical hit varies with TP."},
    [552] = {id=552, en="a line help text"},
    [553] = {id=553, en="a line help text"},
    [554] = {id=554, en="Damage varies with TP."},
    [555] = {id=555, en="Deals earth damage to enemies within a fan-shaped area originating from the caster. Additional effect: Weight."},
    [556] = {id=556, en="a line help text"},
    [557] = {id=557, en="Deals dark damage to an enemy."},
    [558] = {id=558, en="a line help text"},
    [559] = {id=559, en="a line help text"},
    [560] = {id=560, en="Delivers a threefold attack. Damage varies with TP."},
    [561] = {id=561, en="Weakens defense of enemies within range."},
    [562] = {id=562, en="a line help text"},
    [563] = {id=563, en="Deals wind damage to enemies within a fan-shaped area originating from the caster. Additional effect: Blindness."},
    [564] = {id=564, en="Delivers an area attack. Damage varies with TP."},
    [565] = {id=565, en="Deals light damage to enemies within a fan-shaped area originating from the caster. Additional effect: Slow and Silence."},
    [566] = {id=566, en="a line help text"},
    [567] = {id=567, en="Damage varies with TP."},
    [568] = {id=568, en="a line help text"},
    [569] = {id=569, en="Delivers a threefold attack. Accuracy varies with TP."},
    [570] = {id=570, en="Steals an enemy's HP. Ineffective against undead."},
    [571] = {id=571, en="a line help text"},
    [572] = {id=572, en="Lowers Intelligence of enemies within range."},
    [573] = {id=573, en="Reduces an enemy's TP."},
    [574] = {id=574, en="Enhances evasion."},
    [575] = {id=575, en="Enemies within a fan-shaped area originating from the caster are frozen with fear."},
    [576] = {id=576, en="Puts all enemies within range to sleep."},
    [577] = {id=577, en="Deals critical damage. Chance of critical hit varies with TP."},
    [578] = {id=578, en="Restores HP for the target party member."},
    [579] = {id=579, en="Steals one beneficial effect from an enemy."},
    [580] = {id=580, en="a line help text"},
    [581] = {id=581, en="Restores HP for party members within area of effect."},
    [582] = {id=582, en="Silences an enemy."},
    [583] = {id=583, en="a line help text"},
    [584] = {id=584, en="Puts all enemies within range to sleep."},
    [585] = {id=585, en="Damage varies with TP."},
    [586] = {id=586, en="a line help text"},
    [587] = {id=587, en="Damages enemies within area of effect with a twofold attack. Damage varies with TP."},
    [588] = {id=588, en="Gives enemies within range a powerful disease that prevents recovery of HP and MP."},
    [589] = {id=589, en="Damage varies with TP."},
    [590] = {id=590, en="a line help text"},
    [591] = {id=591, en="Deals fire damage to enemies within a fan-shaped area originating from the caster."},
    [592] = {id=592, en="Removes one beneficial magic effect from an enemy."},
    [593] = {id=593, en="Restores HP for the target party member."},
    [594] = {id=594, en="Damage varies with TP."},
    [595] = {id=595, en="Shoots multiple needles at enemies within range."},
    [596] = {id=596, en="Additional effect: Sleep. Duration of effect varies with TP."},
    [597] = {id=597, en="Additional effect: Slow. Duration of effect varies with TP."},
    [598] = {id=598, en="Puts all enemies within range to sleep."},
    [599] = {id=599, en="Additional effect: Poison. Duration of effect varies with TP."},
    [600] = {id=600, en="a line help text"},
    [601] = {id=601, en="a line help text"},
    [602] = {id=602, en="a line help text"},
    [603] = {id=603, en="Additional effect: Vitality Down. Duration of effect varies with TP."},
    [604] = {id=604, en="Deals earth damage that inflicts multiple status ailments on enemies within a fan-shaped area originating from the caster."},
    [605] = {id=605, en="Removes one beneficial magic effect from enemies within range."},
    [606] = {id=606, en="Lowers Strength of enemies within a fan-shaped area originating from the caster."},
    [607] = {id=607, en="a line help text"},
    [608] = {id=608, en="Deals ice damage to enemies within a fan-shaped area originating from the caster. Additional effect: Paralysis."},
    [609] = {id=609, en="a line help text"},
    [610] = {id=610, en="Lowers the evasion of enemies within a fan-shaped area originating from the caster."},
    [611] = {id=611, en="Delivers a fivefold attack. Additional effect: Poison. Accuracy varies with TP."},
    [612] = {id=612, en="Greatly lowers the accuracy of enemies within range for a brief period of time."},
    [613] = {id=613, en="Enhances defense and covers you with magical ice spikes. Enemies that hit you take ice damage."},
    [614] = {id=614, en="Enhances magic defense."},
    [615] = {id=615, en="Covers you with magical lightning spikes. Enemies that hit you take lightning damage."},
    [616] = {id=616, en="Enemies within range are temporarily prevented from acting."},
    [617] = {id=617, en="Damage varies with TP."},
    [618] = {id=618, en="Deals fire damage to enemies within area of effect. Additional effect: 'Bind.'"},
    [619] = {id=619, en="a line help text"},
    [620] = {id=620, en="Delivers an area attack. Additional effect: DEX Down. Duration of effect varies with TP."},
    [621] = {id=621, en="Blinds enemies within a fan-shaped area originating from the caster."},
    [622] = {id=622, en="Delivers an area attack. Damage varies with TP."},
    [623] = {id=623, en="Damage varies with TP. Additional effect: 'Stun.'"},
    [624] = {id=624, en="a line help text"},
    [625] = {id=625, en="a line help text"},
    [626] = {id=626, en="Throws a bomb at an enemy."},
    [627] = {id=627, en="a line help text"},
    [628] = {id=628, en="Delivers an area attack. Additional effect: 'Stun.' Accuracy varies with TP."},
    [629] = {id=629, en="Deals wind damage to enemies within range."},
    [630] = {id=630, en="a line help text"},
    [631] = {id=631, en="Additional effect: Enmity Down. Chance of effect varies with TP."},
    [632] = {id=632, en="Gives party members within range the effect of 'Stoneskin.'"},
    [633] = {id=633, en="Lowers the defense and magical defense of enemies within range."},
    [634] = {id=634, en="Reduces an enemy's TP. Additional effect: Blindness and 'Bind.'"},
    [635] = {id=635, en="a line help text"},
    [636] = {id=636, en="Enhances accuracy and evasion."},
    [637] = {id=637, en="Deals fire damage to an enemy."},
    [638] = {id=638, en="Additional effect: Poison. Chance of effect varies with TP."},
    [639] = {id=639, en="a line help text"},
    [640] = {id=640, en="Delivers an area attack. Additional effect: 'Stun.' Damage varies with TP."},
    [641] = {id=641, en="Delivers a fivefold attack. Damage varies with TP."},
    [642] = {id=642, en="Enhances magic attack and magic defense."},
    [643] = {id=643, en="Damage varies with TP."},
    [644] = {id=644, en="Deals lightning damage to an enemy. Additional effect: Paralysis."},
    [645] = {id=645, en="Restores HP and removes one detrimental magic effect."},
    [646] = {id=646, en="Steals an amount of enemy's MP equal to damage dealt. Ineffective against undead."},
    [647] = {id=647, en="Creates shadow images that each absorb a single attack directed at you."},
    [648] = {id=648, en="Deals water damage to an enemy. Additional effect: Bind."},
    [649] = {id=649, en="a line help text"},
    [650] = {id=650, en="Delivers a threefold attack. Additional effect: Weakens defense. Chance of effect varies with TP."},
    [651] = {id=651, en="Deals water damage to an enemy. Additional effect: Weakens attack and defense."},
    [652] = {id=652, en="Additional effect: Lowers accuracy. Chance of effect varies with TP."},
    [653] = {id=653, en="Delivers a sixfold attack. Accuracy varies with TP."},
    [654] = {id=654, en="Delivers an area attack. Additional effect: Paralysis. Damage varies with TP."},
    [655] = {id=655, en="Enhances attack."},
    [656] = {id=656, en="Deals water damage to enemies within a fan-shaped area originating from the caster. Additional effect: Lowers target's magic defense."},
    [657] = {id=657, en="Deals fire damage to an enemy."},
    [658] = {id=658, en="Restores target party member's HP and enhances attack and magic attack."},
    [659] = {id=659, en="Weakens the attack of enemies within range."},
    [660] = {id=660, en="Reduces the attack speed of enemies within range."},
    [661] = {id=661, en="Increases attack speed."},
    [662] = {id=662, en="Gradually restores MP."},
    [663] = {id=663, en="Deals wind damage to enemies within range."},
    [664] = {id=664, en="Gradually restores HP."},
    [665] = {id=665, en="Deals damage proportional to HP. Reduces HP to 1 after use. Damage varies with TP."},
    [666] = {id=666, en="Delivers a threefold attack. Accuracy varies with TP."},
    [667] = {id=667, en="Damage varies with TP."},
    [668] = {id=668, en="Grants a Magic Shield effect."},
    [669] = {id=669, en="Delivers an area attack that stuns enemies. Damage varies with TP."},
    [670] = {id=670, en="Delivers an area attack that lowers enemies' defense and magic defense. Damage varies with TP."},
    [671] = {id=671, en="Silences and blinds enemies within range."},
    [672] = {id=672, en="Steals an enemy's HP and one beneficial status effect. Ineffective against undead."},
    [673] = {id=673, en="Delivers a fourfold attack. Damage varies with TP."},
    [674] = {id=674, en="Enhances attack and magic attack."},
    [675] = {id=675, en="Deals fire damage to enemies within range. Additional effect: Blindness."},
    [676] = {id=676, en="a line help text"},
    [677] = {id=677, en="Delivers an area attack. Accuracy varies with TP."},
    [678] = {id=678, en="Puts all enemies within range to sleep."},
    [679] = {id=679, en="Creates shadow images that each absorb a single attack directed at you."},
    [680] = {id=680, en="Deals lightning damage to enemies within range."},
    [681] = {id=681, en="Removes one detrimental magic effect for party members within range."},
    [682] = {id=682, en="Delivers a threefold attack. Additional effect: Plague. Effect duration varies with TP."},
    [683] = {id=683, en="Deals dark damage to an enemy."},
    [684] = {id=684, en="Reduces TP for enemies within range."},
    [685] = {id=685, en="Reduces the amount of damage you take."},
    [686] = {id=686, en="Inflicts Doom upon an enemy."},
    [687] = {id=687, en="Deals water damage to enemies within area of effect. Additional effect: Silence."},
    [688] = {id=688, en="Damage varies with TP."},
    [689] = {id=689, en="Deals dark damage to an enemy."},
    [690] = {id=690, en="Restores HP of all party members within range."},
    [691] = {id=691, en="a line help text"},
    [692] = {id=692, en="Damage varies with TP. Additional effect: 'Stun.'"},
    [693] = {id=693, en="Delivers a fourfold attack. Chance of critical hit varies with TP."},
    [694] = {id=694, en="Deals water breath damage to enemies within a fan-shaped area originating from the caster."},
    [695] = {id=695, en="Deals thunder breath damage to enemies within a fan-shaped area originating from the caster."},
    [696] = {id=696, en="Increases the caster's chance of countering."},
    [697] = {id=697, en="Delivers a fivefold attack. Damage varies with TP."},
    [698] = {id=698, en="Deals wind breath damage to enemies within a fan-shaped area originating from the caster."},
    [699] = {id=699, en="Damage varies with TP. Additional effect: Accuracy Down."},
    [700] = {id=700, en="Enhances attack."},
    [701] = {id=701, en="Deals wind damage to enemies within range."},
    [702] = {id=702, en="Deals water damage to enemies within range. Additional effect: Dispel."},
    [703] = {id=703, en="Deals earth damage to enemies within range. Additional effect: Slow."},
    [704] = {id=704, en="Delivers a threefold attack. Additional effect: Paralysis. Damage varies with TP."},
    [705] = {id=705, en="Deals water damage to enemies in a fan-shaped area originating from caster. Additional effect: Drown."},
    [706] = {id=706, en="Damage varies with TP."},
    [707] = {id=707, en="Deals light damage to enemies in a fan-shaped area originating from caster. Additional effect: Flash."},
    [708] = {id=708, en="Deals wind damage to enemies within range. Additional effect: Weight."},
    [709] = {id=709, en="Delivers a fourfold attack. Damage varies with TP."},
    [710] = {id=710, en="Increases attack speed."},
    [711] = {id=711, en="Restores the caster's HP."},
    [712] = {id=712, en="Deals light damage to an enemy."},
    [713] = {id=713, en="Deals light damage to enemies within a fan-shaped area originating from the caster."},
    [714] = {id=714, en="Delivers a fivefold attack. Damage varies with TP."},
    [715] = {id=715, en="Deals wind elemental damage in a fan-shaped area originating from caster."},
    [716] = {id=716, en="Deals water elemental damage to enemies within range. Additional effect: Poison."},
    [717] = {id=717, en="Delivers a twofold attack. Additional effect: Decreases defense Additional effect duration varies with TP."},
    [718] = {id=718, en="Steals HP from enemies within range. Ineffective against undead."},
    [719] = {id=719, en="Deals fire damage to enemies within range. Additional effect: Burn."},
    [720] = {id=720, en="Deals ice damage to enemies within range. Additional effect: Terror."},
    [721] = {id=721, en="Deals lightning damage to enemies within range. Additional effect: Stun."},
    [722] = {id=722, en="Deals earth damage to enemies within range. Additional effect: Petrification."},
    [723] = {id=723, en="Damage varies with TP. Additional effect: Decreases attack."},
    [724] = {id=724, en="Deals darkness damage to enemies within range. Additional effect: Bio."},
    [725] = {id=725, en="Deals light damage to enemies within range. Additional effect: Flash."},
    [726] = {id=726, en="Deals water damage to enemies within range. Additional effect: Decreases attack."},
    [727] = {id=727, en="Deals wind damage to enemies within range. Additional effect: Silence."},
    [728] = {id=728, en="Deals darkness damage to enemies within range. Additional effect: Decreases defense."},
    [729] = {id=729, en="a line help text"},
    [730] = {id=730, en="a line help text"},
    [731] = {id=731, en="a line help text"},
    [732] = {id=732, en="a line help text"},
    [733] = {id=733, en="a line help text"},
    [734] = {id=734, en="a line help text"},
    [735] = {id=735, en="a line help text"},
    [736] = {id=736, en="Deals lightning damage to enemies within range. Additional effect: 'Stun.'"},
    [737] = {id=737, en="Enhances defense."},
    [738] = {id=738, en="Freezes target in fear."},
    [739] = {id=739, en="Deals fire damage to enemies within range. Additional effect: 'Burn.'"},
    [740] = {id=740, en="Delivers an area attack. Additional effect duration varies with TP. Additional effect: Weakens defense."},
    [741] = {id=741, en="Resists physical damage."},
    [742] = {id=742, en="Delivers an area attack. Additional effect duration varies with TP. Additional effect: Lowers attack, defense, and accuracy."},
    [743] = {id=743, en="Delivers a threefold attack. Damage varies with TP. Additional effect: HP Drain."},
    [744] = {id=744, en="Deals wind damage to enemies within range. Additional effect: Dispel."},
    [745] = {id=745, en="Enhances attack and magic attack. Reduces spell interruption rate."},
    [746] = {id=746, en="Enemies within range are frozen with fear."},
    [747] = {id=747, en="Deals light damage to enemies within range. Also removes status ailments from caster."},
    [748] = {id=748, en="Deals lightning damage to enemies within range."},
    [749] = {id=749, en="Deals ice damage to enemies within range. Additional effect: Bind."},
    [750] = {id=750, en="Increases own defense, magic defenses, and attack speed, and gradually restores own HP."},
    [751] = {id=751, en="Inflicts Doom upon enemies within range."},
    [752] = {id=752, en="Deals water damage to enemies within range. Additional effect: Plague."},
    [753] = {id=753, en="Deals wind damage to enemies within range. Additional effect: Weakens magic defense."},
    [754] = {id=754, en="a line help text"},
    [755] = {id=755, en="a line help text"},
    [756] = {id=756, en="a line help text"},
    [757] = {id=757, en="a line help text"},
    [758] = {id=758, en="a line help text"},
    [759] = {id=759, en="a line help text"},
    [760] = {id=760, en="a line help text"},
    [761] = {id=761, en="a line help text"},
    [762] = {id=762, en="a line help text"},
    [763] = {id=763, en="a line help text"},
    [764] = {id=764, en="a line help text"},
    [765] = {id=765, en="a line help text"},
    [766] = {id=766, en="a line help text"},
    [767] = {id=767, en="a line help text"},
    [768] = {id=768, en="Gradually restores HP for party members within range."},
    [769] = {id=769, en="Poisons enemies within range and gradually reduces their HP."},
    [770] = {id=770, en="Gradually restores MP for party members within range."},
    [771] = {id=771, en="Increases attack speed for party members within range."},
    [772] = {id=772, en="Enhances Strength for party members within range."},
    [773] = {id=773, en="Enhances Dexterity for party members within range."},
    [774] = {id=774, en="Enhances Vitality for party members within range."},
    [775] = {id=775, en="Enhances Agility for party members within range."},
    [776] = {id=776, en="Enhances Intelligence for party members within range."},
    [777] = {id=777, en="Enhances Mind for party members within range."},
    [778] = {id=778, en="Enhances Charisma for party members within range."},
    [779] = {id=779, en="Enhances attack for party members within range."},
    [780] = {id=780, en="Enhances defense for party members within range."},
    [781] = {id=781, en="Enhances magic attack for party members within range."},
    [782] = {id=782, en="Enhances magic defense for party members within range."},
    [783] = {id=783, en="Enhances accuracy for party members within range."},
    [784] = {id=784, en="Enhances evasion for party members within range."},
    [785] = {id=785, en="Enhances magic accuracy for party members within range."},
    [786] = {id=786, en="Enhances magic evasion for party members within range."},
    [787] = {id=787, en="Reduces attack for enemies within range."},
    [788] = {id=788, en="Reduces defense for enemies within range."},
    [789] = {id=789, en="Reduces magic attack for enemies within range."},
    [790] = {id=790, en="Reduces magic defense for enemies within range."},
    [791] = {id=791, en="Reduces accuracy for enemies within range."},
    [792] = {id=792, en="Reduces evasion for enemies within range."},
    [793] = {id=793, en="Reduces magic accuracy for enemies within range."},
    [794] = {id=794, en="Reduces magic evasion for enemies within range."},
    [795] = {id=795, en="Reduces attack speed for enemies within range."},
    [796] = {id=796, en="Paralyzes enemies within range."},
    [797] = {id=797, en="Weighs down enemies within range and lowers their movement speed."},
    [798] = {id=798, en="Gradually restores HP for party members within area of effect."},
    [799] = {id=799, en="Poisons enemies within area of effect and gradually reduces their HP."},
    [800] = {id=800, en="Gradually restores MP for party members within area of effect."},
    [801] = {id=801, en="Increases attack speed for party members within area of effect."},
    [802] = {id=802, en="Enhances Strength for party members within area of effect."},
    [803] = {id=803, en="Enhances Dexterity for party members within area of effect."},
    [804] = {id=804, en="Enhances Vitality for party members within area of effect."},
    [805] = {id=805, en="Enhances Agility for party members within area of effect."},
    [806] = {id=806, en="Enhances Intelligence for party members within area of effect."},
    [807] = {id=807, en="Enhances Mind for party members within area of effect."},
    [808] = {id=808, en="Enhances Charisma for party members within area of effect."},
    [809] = {id=809, en="Enhances attack for party members within area of effect."},
    [810] = {id=810, en="Enhances defense for party members within area of effect."},
    [811] = {id=811, en="Enhances magic attack for party members within area of effect."},
    [812] = {id=812, en="Enhances magic defense for party members within area of effect."},
    [813] = {id=813, en="Enhances accuracy for party members within area of effect."},
    [814] = {id=814, en="Enhances evasion for party members within area of effect."},
    [815] = {id=815, en="Enhances magic accuracy for party members within area of effect."},
    [816] = {id=816, en="Enhances magic evasion for party members within area of effect."},
    [817] = {id=817, en="Reduces attack for enemies within area of effect."},
    [818] = {id=818, en="Reduces defense for enemies within area of effect."},
    [819] = {id=819, en="Reduces magic attack for enemies within area of effect."},
    [820] = {id=820, en="Reduces magic defense for enemies within area of effect."},
    [821] = {id=821, en="Reduces accuracy for enemies within area of effect."},
    [822] = {id=822, en="Reduces evasion for enemies within area of effect."},
    [823] = {id=823, en="Reduces magic accuracy for enemies within area of effect."},
    [824] = {id=824, en="Reduces magic evasion for enemies within area of effect."},
    [825] = {id=825, en="Reduces attack speed for enemies within area of effect."},
    [826] = {id=826, en="Paralyzes enemies within area of effect."},
    [827] = {id=827, en="Weighs down enemies within area of effect and lowers their movement speed."},
    [828] = {id=828, en="Deals fire damage to enemies within area of effect."},
    [829] = {id=829, en="Deals fire damage to enemies within area of effect."},
    [830] = {id=830, en="Deals ice damage to enemies within area of effect."},
    [831] = {id=831, en="Deals ice damage to enemies within area of effect."},
    [832] = {id=832, en="Deals wind damage to enemies within area of effect."},
    [833] = {id=833, en="Deals wind damage to enemies within area of effect."},
    [834] = {id=834, en="Deals earth damage to enemies within area of effect."},
    [835] = {id=835, en="Deals earth damage to enemies within area of effect."},
    [836] = {id=836, en="Deals lightning damage to enemies within area of effect."},
    [837] = {id=837, en="Deals lightning damage to enemies within area of effect."},
    [838] = {id=838, en="Deals water damage to enemies within area of effect."},
    [839] = {id=839, en="Deals water damage to enemies within area of effect."},
    [840] = {id=840, en="Enhances evasion against special attacks."},
    [841] = {id=841, en="Reduces an enemy's physical evasion."},
    [842] = {id=842, en="Reduces an enemy's physical evasion."},
    [843] = {id=843, en="Reduces an enemy's magic evasion."},
    [844] = {id=844, en="Reduces an enemy's magic evasion."},
    [845] = {id=845, en="Increases target's ranged attack speed."},
    [846] = {id=846, en="Increases target's ranged attack speed."},
    [847] = {id=847, en="Summons Atomos to fight by your side."},
    [848] = {id=848, en="Grants you the effect of Raise with a decreased weakness duration when you are KO'd."},
    [849] = {id=849, en="Deals fire damage to an enemy."},
    [850] = {id=850, en="Deals ice damage to an enemy."},
    [851] = {id=851, en="Deals wind damage to an enemy."},
    [852] = {id=852, en="Deals earth damage to an enemy."},
    [853] = {id=853, en="Deals lightning damage to an enemy."},
    [854] = {id=854, en="Deals water damage to an enemy."},
    [855] = {id=855, en="Adds light damage to your attacks."},
    [856] = {id=856, en="Adds darkness damage to your attacks."},
    [857] = {id=857, en="Changes the weather around target party member to 'dusty.'"},
    [858] = {id=858, en="Changes the weather around target party member to 'rainy.'"},
    [859] = {id=859, en="Changes the weather around target party member to 'windy.'"},
    [860] = {id=860, en="Changes the weather around target party member to 'hot.'"},
    [861] = {id=861, en="Changes the weather around target party member to 'snowy.'"},
    [862] = {id=862, en="Changes the weather around target party member to 'thundery.'"},
    [863] = {id=863, en="Changes the weather around target party member to 'gloomy.'"},
    [864] = {id=864, en="Changes the weather around target party member to 'auroras.'"},
    [865] = {id=865, en="Deals fire damage to enemies within area of effect."},
    [866] = {id=866, en="Deals ice damage to enemies within area of effect."},
    [867] = {id=867, en="Deals wind damage to enemies within area of effect."},
    [868] = {id=868, en="Deals earth damage to enemies within area of effect."},
    [869] = {id=869, en="Deals lightning damage to enemies within area of effect."},
    [870] = {id=870, en="Deals water damage to enemies within area of effect."},
    [871] = {id=871, en="Reduces an enemy's resistance against fire."},
    [872] = {id=872, en="Reduces an enemy's resistance against ice."},
    [873] = {id=873, en="Reduces an enemy's resistance against wind."},
    [874] = {id=874, en="Reduces an enemy's resistance against earth."},
    [875] = {id=875, en="Reduces an enemy's resistance against lightning."},
    [876] = {id=876, en="Reduces an enemy's resistance against water."},
    [877] = {id=877, en="Reduces an enemy's resistance against light."},
    [878] = {id=878, en="Reduces an enemy's resistance against darkness."},
    [879] = {id=879, en="Grants a bonus to skillchain damage based on the number of successful melee hits."},
    [880] = {id=880, en="Steals an enemy's HP, potentially increasing maximum HP. Ineffective against undead."},
    [881] = {id=881, en="Steals an enemy's MP. Ineffective against undead."},
    [882] = {id=882, en="Reduces an enemy's physical evasion."},
    [883] = {id=883, en="Reduces an enemy's magic evasion."},
    [884] = {id=884, en="Decreases an enemy's magic accuracy and increases its spellcasting time."},
    [885] = {id=885, en="Deals earth damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [886] = {id=886, en="Deals water damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [887] = {id=887, en="Deals wind damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [888] = {id=888, en="Deals fire damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [889] = {id=889, en="Deals ice damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [890] = {id=890, en="Deals lightning damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [891] = {id=891, en="Deals darkness damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [892] = {id=892, en="Deals light damage that gradually reduces a target's HP. Damage dealt is greatly affected by the weather."},
    [893] = {id=893, en="Consumes all MP. Restores target's HP and cures status ailments. Afflatus Solace: Grants the effect of 'Stoneskin.'"},
    [894] = {id=894, en="Gradually restores target's MP."},
    [895] = {id=895, en="Grants the ability to occasionally attack thrice."},
    [896] = {id=896, en="Calls an alter ego of Shantotto."},
    [897] = {id=897, en="Calls an alter ego of Naji."},
    [898] = {id=898, en="Calls an alter ego of Kupipi."},
    [899] = {id=899, en="Calls an alter ego of Excenmille."},
    [900] = {id=900, en="Calls an alter ego of Ayame."},
    [901] = {id=901, en="Calls an alter ego of Nanaa Mihgo."},
    [902] = {id=902, en="Calls an alter ego of Curilla."},
    [903] = {id=903, en="Calls an alter ego of Volker."},
    [904] = {id=904, en="Calls an alter ego of Ajido-Marujido."},
    [905] = {id=905, en="Calls an alter ego of Trion."},
    [906] = {id=906, en="Calls an alter ego of Zeid."},
    [907] = {id=907, en="Calls an alter ego of Lion."},
    [908] = {id=908, en="Calls an alter ego of Tenzen."},
    [909] = {id=909, en="Calls an alter ego of Mihli Aliapoh."},
    [910] = {id=910, en="Calls an alter ego of Valaineral [S]."},
    [911] = {id=911, en="Calls an alter ego of Joachim."},
    [912] = {id=912, en="Calls an alter ego of Naja Salaheem."},
    [913] = {id=913, en="Calls an alter ego of Prishe."},
    [914] = {id=914, en="Calls an alter ego of Ulmia."},
    [915] = {id=915, en="Calls an alter ego of Shikaree Z."},
    [916] = {id=916, en="Calls an alter ego of Cherukiki."},
    [917] = {id=917, en="Calls an alter ego of Iron Eater."},
    [918] = {id=918, en="Calls an alter ego of Gessho."},
    [919] = {id=919, en="Calls an alter ego of Gadalar."},
    [920] = {id=920, en="Calls an alter ego of Rainemard [S]."},
    [921] = {id=921, en="Calls an alter ego of Ingrid."},
    [922] = {id=922, en="Calls an alter ego of Lehko Habhoka [S]."},
    [923] = {id=923, en="Calls an alter ego of Nashmeira."},
    [924] = {id=924, en="Calls an alter ego of Zazarg."},
    [925] = {id=925, en="Calls an alter ego of Ovjang."},
    [926] = {id=926, en="Calls an alter ego of Mnejing."},
    [927] = {id=927, en="Calls an alter ego of Sakura."},
    [928] = {id=928, en="Calls an alter ego of Luzaf."},
    [929] = {id=929, en="Calls an alter ego of Najelith."},
    [930] = {id=930, en="Calls an alter ego of Aldo."},
    [931] = {id=931, en="Calls an alter ego of a moogle."},
    [932] = {id=932, en="Calls an alter ego of Fablinix."},
    [933] = {id=933, en="Calls an alter ego of Maat."},
    [934] = {id=934, en="Calls an alter ego of Domina Shantotto."},
    [935] = {id=935, en="Calls an alter ego of the Star Sibyl."},
    [936] = {id=936, en="Calls an alter ego of Karaha-Baruha [S]."},
    [937] = {id=937, en="Calls an alter ego of Cid."},
    [938] = {id=938, en="Calls an alter ego of Gilgamesh."},
    [939] = {id=939, en="Calls an alter ego of Areuhat."},
    [940] = {id=940, en="Calls an alter ego of Semih Lafihna."},
    [941] = {id=941, en="Calls an alter ego of Elivira [S]."},
    [942] = {id=942, en="Calls an alter ego of Noillurie [S]."},
    [943] = {id=943, en="Calls an alter ego of Lhu Mhakaracca [S]."},
    [944] = {id=944, en="Calls an alter ego of Ferreous Coffin [S]."},
    [945] = {id=945, en="Calls an alter ego of Lilisette."},
    [946] = {id=946, en="Calls an alter ego of Mumor."},
    [947] = {id=947, en="Calls an alter ego of Uka Totlihn."},
    [948] = {id=948, en="Calls an alter ego of Klara [S]."},
    [949] = {id=949, en="Calls an alter ego of Romaa Mihgo [S]."},
    [950] = {id=950, en="Calls an alter ego of Kuyin Hathdenna."},
    [951] = {id=951, en="Calls an alter ego of Rahal."},
    [952] = {id=952, en="Calls an alter ego of Koru-Moru."},
    [953] = {id=953, en="Calls an alter ego of Pieuje (UC)."},
    [954] = {id=954, en="Calls an alter ego of Invincible Shield (UC)."},
    [955] = {id=955, en="Calls an alter ego of Apururu (UC)."},
    [956] = {id=956, en="Calls an alter ego of Jakoh Wahcondalo (UC)."},
    [957] = {id=957, en="Calls an alter ego of Flaviria (UC)."},
    [958] = {id=958, en="Calls an alter ego of Babban Ny Mheillea."},
    [959] = {id=959, en="Calls an alter ego of Abenzio."},
    [960] = {id=960, en="Calls an alter ego of Rughadjeen."},
    [961] = {id=961, en="Calls an alter ego of Kukki-Chebukki."},
    [962] = {id=962, en="Calls an alter ego of Margret."},
    [963] = {id=963, en="Calls an alter ego of Chacharoon."},
    [964] = {id=964, en="Calls an alter ego of Lhe Lhangavo."},
    [965] = {id=965, en="Calls an alter ego of Arciela."},
    [966] = {id=966, en="Calls an alter ego of Mayakov."},
    [967] = {id=967, en="Calls an alter ego of Qultada."},
    [968] = {id=968, en="Calls an alter ego of Adelheid [S]."},
    [969] = {id=969, en="Calls an alter ego of Amchuchu."},
    [970] = {id=970, en="Calls an alter ego of Brygid."},
    [971] = {id=971, en="Calls an alter ego of Mildaurion."},
    [972] = {id=972, en="Calls an alter ego of Halver."},
    [973] = {id=973, en="Calls an alter ego of Rongelouts."},
    [974] = {id=974, en="Calls an alter ego of Leonoyne."},
    [975] = {id=975, en="Calls an alter ego of Maximilian."},
    [976] = {id=976, en="Calls an alter ego of Kayeel-Payeel."},
    [977] = {id=977, en="Calls an alter ego of Robel-Akbel."},
    [978] = {id=978, en="Calls an alter ego of Kupofried."},
    [979] = {id=979, en="Calls an alter ego of Selh'teus."},
    [980] = {id=980, en="Calls an alter ego of Yoran-Oran (UC)."},
    [981] = {id=981, en="Calls an alter ego of Sylvie (UC)."},
    [982] = {id=982, en="Calls an alter ego of Abquhbah."},
    [983] = {id=983, en="Calls an alter ego of Balamor."},
    [984] = {id=984, en="Calls an alter ego of August."},
    [985] = {id=985, en="Calls an alter ego of Rosulatia."},
    [986] = {id=986, en="Calls an alter ego of Teodor."},
    [987] = {id=987, en="Calls an alter ego of Ullegore."},
    [988] = {id=988, en="Calls an alter ego of Makki-Chebukki."},
    [989] = {id=989, en="Calls an alter ego of the King of Hearts."},
    [990] = {id=990, en="Calls an alter ego of Morimar."},
    [991] = {id=991, en="Calls an alter ego of Darrcuiln."},
    [992] = {id=992, en="Calls an alter ego of Ark Angel HM."},
    [993] = {id=993, en="Calls an alter ego of Ark Angel EV."},
    [994] = {id=994, en="Calls an alter ego of Ark Angel MR."},
    [995] = {id=995, en="Calls an alter ego of Ark Angel TT."},
    [996] = {id=996, en="Calls an alter ego of Ark Angel GK."},
    [997] = {id=997, en="Calls an alter ego of Iroha."},
    [998] = {id=998, en="Calls an alter ego of Ygnas."},
    [999] = {id=999, en="Calls an alter ego of Monberaux."},
    [1000] = {id=1000, en="nothing."},
    [1001] = {id=1001, en="nothing."},
    [1002] = {id=1002, en="nothing."},
    [1003] = {id=1003, en="."},
    [1004] = {id=1004, en="Calls an alter ego of Excenmille [S]."},
    [1005] = {id=1005, en="Calls an alter ego of Ayame (UC)."},
    [1006] = {id=1006, en="Calls an alter ego of Maat (UC)."},
    [1007] = {id=1007, en="Calls an alter ego of Aldo (UC)."},
    [1008] = {id=1008, en="Calls an alter ego of Naja Salaheem (UC)."},
    [1009] = {id=1009, en="Calls an alter ego of Lion [RoV]."},
    [1010] = {id=1010, en="Calls an alter ego of Zeid [RoV]."},
    [1011] = {id=1011, en="Calls an alter ego of Prishe [RoV]."},
    [1012] = {id=1012, en="Calls an alter ego of Nashmeira [RoV]."},
    [1013] = {id=1013, en="Calls an alter ego of Lilisette [RoV]."},
    [1014] = {id=1014, en="Calls an alter ego of Tenzen [RoV]."},
    [1015] = {id=1015, en="Calls an alter ego of Mumor II."},
    [1016] = {id=1016, en="Calls an alter ego of Ingrid II."},
    [1017] = {id=1017, en="Calls an alter ego of Arciela [RoV]."},
    [1018] = {id=1018, en="Calls an alter ego of Iroha [RoV]."},
    [1019] = {id=1019, en="Calls an alter ego of Shantotto II."},
    [1020] = {id=1020, en="nothing."},
    [1021] = {id=1021, en="nothing."},
    [1022] = {id=1022, en="nothing."},
    [1023] = {id=1023, en="nothing."},
}, {"id", "en"}